### ISSUE TITLE
화면이 큰 기기에서 MakeBook 글자가 왼쪽으로 치우침

### ISSUE THREAD

**Issue by kim-jhyeon** [howtolivelikehuman/MakeBook#24]
태블릿 등의 화면이 큰 기기에서 로딩 화면의 MakeBook 글자가 정렬되어있지 않은 문제를 발견하였습니다.

![Peek 2021-06-09 19-33](https://user-images.githubusercontent.com/49356944/121339717-b9b74480-c959-11eb-9d25-22a4cf2040a4.gif)

**Comment by howtolivelikehuman** [comment]
수정해서 풀리퀘날렸습니당
